#!/bin/sh

#LOCAL_HOOK=$HOME/.git_template/hooks/post-checkout
#[[ -f $LOCAL_HOOK ]] && source $LOCAL_HOOK

#git submodule update --init --recursive

.git/hooks/ctags >/dev/null 2>&1 &
.git/hooks/cscope >/dev/null 2>&1 &
